### ISSUE TITLE
Script to manage JSON files

### ISSUE THREAD

**Issue by jay-donovan** [302Development/Database#6]
rename these file and delete any older than a week.

**Comment by MitchPannas** [comment]
`find /path/to/files/ -type f -name '*.json' -mtime +7 -exec rm {} \;

find /path/to/files/ -type f -name '*.json' -mmin +59 -exec mv {} /path/to/archive/ \;`

Directories to be changed, 2nd command will only move not copy and move (okay if json file is being created constantly)
